// Mocks generated by Mockito 5.4.6 from annotations
// in lg_flutter_stater_kit/test/data/datasources/ssh_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;
import 'dart:typed_data' as _i4;

import 'package:lg_flutter_stater_kit/domain/services/ssh_service_interface.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [ISshService].
///
/// See the documentation for Mockito's code generation for more information.
class MockISshService extends _i1.Mock implements _i2.ISshService {
  MockISshService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isConnected => (super.noSuchMethod(
        Invocation.getter(#isConnected),
        returnValue: false,
      ) as bool);

  @override
  set onConnectionLost(void Function()? callback) => super.noSuchMethod(
        Invocation.setter(
          #onConnectionLost,
          callback,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i3.Future<void> connect(
    String? ip,
    String? password,
    String? user,
    int? port,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #connect,
          [
            ip,
            password,
            user,
            port,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> disconnect() => (super.noSuchMethod(
        Invocation.method(
          #disconnect,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<String?> execute(String? cmd) => (super.noSuchMethod(
        Invocation.method(
          #execute,
          [cmd],
        ),
        returnValue: _i3.Future<String?>.value(),
      ) as _i3.Future<String?>);

  @override
  _i3.Future<void> uploadViaSftp(
    String? content,
    String? remotePath,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #uploadViaSftp,
          [
            content,
            remotePath,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> uploadBytesViaSftp(
    _i4.Uint8List? bytes,
    String? remotePath,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #uploadBytesViaSftp,
          [
            bytes,
            remotePath,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
