// Mocks generated by Mockito 5.4.6 from annotations
// in lg_flutter_stater_kit/test/data/repositories/lg_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:lg_flutter_stater_kit/data/datasources/local_storage_source.dart'
    as _i4;
import 'package:lg_flutter_stater_kit/data/datasources/ssh_service.dart' as _i2;
import 'package:lg_flutter_stater_kit/domain/entities/connection_entity.dart'
    as _i5;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [SshService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSshService extends _i1.Mock implements _i2.SshService {
  MockSshService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isConnected => (super.noSuchMethod(
        Invocation.getter(#isConnected),
        returnValue: false,
      ) as bool);

  @override
  set onConnectionLost(void Function()? value) => super.noSuchMethod(
        Invocation.setter(
          #onConnectionLost,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i3.Future<void> connect(
    String? ip,
    String? password,
    String? user,
    int? port,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #connect,
          [
            ip,
            password,
            user,
            port,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> disconnect() => (super.noSuchMethod(
        Invocation.method(
          #disconnect,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<String?> execute(String? cmd) => (super.noSuchMethod(
        Invocation.method(
          #execute,
          [cmd],
        ),
        returnValue: _i3.Future<String?>.value(),
      ) as _i3.Future<String?>);

  @override
  _i3.Future<void> uploadViaSftp(
    String? content,
    String? remotePath,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #uploadViaSftp,
          [
            content,
            remotePath,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [LocalStorageDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocalStorageDataSource extends _i1.Mock
    implements _i4.LocalStorageDataSource {
  MockLocalStorageDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> saveSettings(_i5.ConnectionEntity? connection) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveSettings,
          [connection],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<_i5.ConnectionEntity?> loadSettings() => (super.noSuchMethod(
        Invocation.method(
          #loadSettings,
          [],
        ),
        returnValue: _i3.Future<_i5.ConnectionEntity?>.value(),
      ) as _i3.Future<_i5.ConnectionEntity?>);

  @override
  _i3.Future<void> clearSettings() => (super.noSuchMethod(
        Invocation.method(
          #clearSettings,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}
