// Mocks generated by Mockito 5.4.6 from annotations
// in lg_flutter_stater_kit/test/data/repositories/places_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:lg_flutter_stater_kit/core/constant/log_service.dart' as _i2;
import 'package:lg_flutter_stater_kit/data/datasources/places_remote_datasource.dart'
    as _i3;
import 'package:lg_flutter_stater_kit/data/models/fly_to_model.dart' as _i6;
import 'package:lg_flutter_stater_kit/data/models/place_model.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeLogService_0 extends _i1.SmartFake implements _i2.LogService {
  _FakeLogService_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [PlacesRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockPlacesRemoteDataSource extends _i1.Mock
    implements _i3.PlacesRemoteDataSource {
  MockPlacesRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.LogService get log => (super.noSuchMethod(
        Invocation.getter(#log),
        returnValue: _FakeLogService_0(
          this,
          Invocation.getter(#log),
        ),
      ) as _i2.LogService);

  @override
  _i4.Future<List<_i5.PlaceModel>> searchPlaces(String? query) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchPlaces,
          [query],
        ),
        returnValue: _i4.Future<List<_i5.PlaceModel>>.value(<_i5.PlaceModel>[]),
      ) as _i4.Future<List<_i5.PlaceModel>>);

  @override
  _i4.Future<_i6.FlyToModel?> getPlaceDetails(String? placeId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPlaceDetails,
          [placeId],
        ),
        returnValue: _i4.Future<_i6.FlyToModel?>.value(),
      ) as _i4.Future<_i6.FlyToModel?>);
}
