// Mocks generated by Mockito 5.4.6 from annotations
// in lg_flutter_stater_kit/test/ui/pages/setting_page_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;
import 'dart:typed_data' as _i8;

import 'package:lg_flutter_stater_kit/domain/entities/connection_entity.dart'
    as _i4;
import 'package:lg_flutter_stater_kit/domain/entities/fly_to_entity.dart'
    as _i5;
import 'package:lg_flutter_stater_kit/domain/entities/orbit_entity.dart' as _i6;
import 'package:lg_flutter_stater_kit/domain/repositories/lg_repository.dart'
    as _i2;
import 'package:lg_flutter_stater_kit/domain/services/ssh_service_interface.dart'
    as _i7;
import 'package:lg_flutter_stater_kit/domain/usecases/connect_to_lg.dart'
    as _i9;
import 'package:lg_flutter_stater_kit/domain/usecases/system_control.dart'
    as _i10;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeLGRepository_0 extends _i1.SmartFake implements _i2.LGRepository {
  _FakeLGRepository_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [LGRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockLGRepository extends _i1.Mock implements _i2.LGRepository {
  MockLGRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isConnected => (super.noSuchMethod(
        Invocation.getter(#isConnected),
        returnValue: false,
      ) as bool);

  @override
  int get screenNumber => (super.noSuchMethod(
        Invocation.getter(#screenNumber),
        returnValue: 0,
      ) as int);

  @override
  _i3.Future<void> connect(
    String? ip,
    String? username,
    String? password,
    int? port,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #connect,
          [
            ip,
            username,
            password,
            port,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> disconnect() => (super.noSuchMethod(
        Invocation.method(
          #disconnect,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> storeSettings(
    String? ip,
    String? username,
    String? password,
    int? port, {
    int? screenNumber = 3,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #storeSettings,
          [
            ip,
            username,
            password,
            port,
          ],
          {#screenNumber: screenNumber},
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<_i4.ConnectionEntity?> getSettings() => (super.noSuchMethod(
        Invocation.method(
          #getSettings,
          [],
        ),
        returnValue: _i3.Future<_i4.ConnectionEntity?>.value(),
      ) as _i3.Future<_i4.ConnectionEntity?>);

  @override
  _i3.Future<void> setScreenNumber(int? screens) => (super.noSuchMethod(
        Invocation.method(
          #setScreenNumber,
          [screens],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> flyTo(_i5.FlyToEntity? command) => (super.noSuchMethod(
        Invocation.method(
          #flyTo,
          [command],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> sendQuery(String? query) => (super.noSuchMethod(
        Invocation.method(
          #sendQuery,
          [query],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> uploadKml(
    String? content,
    String? fileName,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #uploadKml,
          [
            content,
            fileName,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> sendKmlToSlave(
    String? kmlContent,
    int? screen,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendKmlToSlave,
          [
            kmlContent,
            screen,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> sendKmlToMaster(String? kmlContent) => (super.noSuchMethod(
        Invocation.method(
          #sendKmlToMaster,
          [kmlContent],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> cleanAllKml() => (super.noSuchMethod(
        Invocation.method(
          #cleanAllKml,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> clearNavigation() => (super.noSuchMethod(
        Invocation.method(
          #clearNavigation,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> sendLogo({String? assetPath = 'image/logo.png'}) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendLogo,
          [],
          {#assetPath: assetPath},
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> cleanLogo() => (super.noSuchMethod(
        Invocation.method(
          #cleanLogo,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> sendHtmlOverlay(String? htmlContent) => (super.noSuchMethod(
        Invocation.method(
          #sendHtmlOverlay,
          [htmlContent],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> orbit(_i6.OrbitEntity? orbitParams) => (super.noSuchMethod(
        Invocation.method(
          #orbit,
          [orbitParams],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<bool> rebootAll() => (super.noSuchMethod(
        Invocation.method(
          #rebootAll,
          [],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<bool> shutdownAll() => (super.noSuchMethod(
        Invocation.method(
          #shutdownAll,
          [],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<void> relaunch() => (super.noSuchMethod(
        Invocation.method(
          #relaunch,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> forceRefresh(int? screenNumber) => (super.noSuchMethod(
        Invocation.method(
          #forceRefresh,
          [screenNumber],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}

/// A class which mocks [ISshService].
///
/// See the documentation for Mockito's code generation for more information.
class MockISshService extends _i1.Mock implements _i7.ISshService {
  MockISshService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isConnected => (super.noSuchMethod(
        Invocation.getter(#isConnected),
        returnValue: false,
      ) as bool);

  @override
  set onConnectionLost(void Function()? callback) => super.noSuchMethod(
        Invocation.setter(
          #onConnectionLost,
          callback,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i3.Future<void> connect(
    String? ip,
    String? password,
    String? user,
    int? port,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #connect,
          [
            ip,
            password,
            user,
            port,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> disconnect() => (super.noSuchMethod(
        Invocation.method(
          #disconnect,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<String?> execute(String? cmd) => (super.noSuchMethod(
        Invocation.method(
          #execute,
          [cmd],
        ),
        returnValue: _i3.Future<String?>.value(),
      ) as _i3.Future<String?>);

  @override
  _i3.Future<void> uploadViaSftp(
    String? content,
    String? remotePath,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #uploadViaSftp,
          [
            content,
            remotePath,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> uploadBytesViaSftp(
    _i8.Uint8List? bytes,
    String? remotePath,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #uploadBytesViaSftp,
          [
            bytes,
            remotePath,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [ConnectToLgUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockConnectToLgUseCase extends _i1.Mock
    implements _i9.ConnectToLgUseCase {
  MockConnectToLgUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.LGRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeLGRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.LGRepository);

  @override
  _i3.Future<void> call(
    String? ip,
    String? username,
    String? password,
    int? port,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [
            ip,
            username,
            password,
            port,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}

/// A class which mocks [DisconnectFromLgUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockDisconnectFromLgUseCase extends _i1.Mock
    implements _i9.DisconnectFromLgUseCase {
  MockDisconnectFromLgUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.LGRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeLGRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.LGRepository);

  @override
  _i3.Future<void> call() => (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}

/// A class which mocks [RebootLgUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockRebootLgUseCase extends _i1.Mock implements _i10.RebootLgUseCase {
  MockRebootLgUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.LGRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeLGRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.LGRepository);

  @override
  _i3.Future<bool> call() => (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);
}

/// A class which mocks [RelaunchLgUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockRelaunchLgUseCase extends _i1.Mock implements _i10.RelaunchLgUseCase {
  MockRelaunchLgUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.LGRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeLGRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.LGRepository);

  @override
  _i3.Future<void> call() => (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}

/// A class which mocks [ShutdownLgUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockShutdownLgUseCase extends _i1.Mock implements _i10.ShutdownLgUseCase {
  MockShutdownLgUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.LGRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeLGRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.LGRepository);

  @override
  _i3.Future<bool> call() => (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);
}
